disp('Loading Data');
load('rawTrain.mat');
load('rawTest.mat');
disp('Discretizing Data');
discreteTrainX = round(rawTrainX * 10^6 + 10^7);
discreteTest = round(rawTest * 10^6 + 10^7);
clearvars rawTrainX rawTest;
disp('Generating Transition and Emission Matrices');
[trans,emis] = hmmestimate(discreteTrainX, rawTrainY);
trans_hat = zeros(7,7);
trans_hat(2:7,2:7) = trans;
trans_hat(1,2:7) = 1/6;
emis_hat = [zeros(size(emis(1,:))); emis];
disp('Done');
